// Hardcode...
// But it's ok

WORDS = {
    'Firebird|Firebird': 'Protelançachamas|Lança-Chamas',
    'Smoky|Smoky': 'Protefumegante|Canhão-Fumegante',
    'Twins|Twins': 'Protegemeos|Gêmeos',
    'Railgun|Railgun': 'Protecanhaoeletrico|Canhão-Elétrico',
    'HammerProt|Hammer': 'Protemartelo|Martelo',
    'Isida|Isida': 'Proteisida|Isida',
    'Vulcan_rez|Vulcan': 'Protevulcao|Vulcão',
    'Thunder|Thunder': 'Protetrovao|Trovão',
    'Freeze|Freeze': 'Protelançagelo|Lança-Gelo',
    'Ricochet|Ricochet': 'Protericochete|Ricochete',
    'Shaft|Shaft': 'Proteshaft|Shaft',
    "Main article: '''[[Paints]]'''": "''Artigo Principal:'' '''[[Pinturas]]'''",
    "''Main article:'' '''[[Paints]]'''": "''Artigo Principal:'' '''[[Pinturas]]'''",
    'Basic': 'Básica',
    'Crysmini': 'MiniCry',
    /*'Recruit': 'Recruta',
    'Private': 'Soldado',
    'Gefreiter': 'Taifeiro',
    'Corporal': 'Cabo',
    'Master Corporal': 'Taifeiro-mor',
    'Sergeant': 'Sargento',
    'Staff Sergeant': 'Terceiro-sargento',
    'Master Sergeant': 'Segundo-sargento',
    'First Sergeant': 'Primeiro-sargento',
    'Sergeant-Major': 'Sargento-mor',
    'Warrant Officer 1': 'Subtenente 1',
    'Warrant Officer 2': 'Subtenente 2',
    'Warrant Officer 3': 'Subtenente 3',
    'Warrant Officer 4': 'Subtenente 4',
    'Warrant Officer 5': 'Subtenente 5',
    'Third Lieutenant': 'Aspirante-a-Oficial',
    'Second Lieutenant': 'Segundo-tenente',
    'First Lieutenant': 'Primeiro-tenente',
    'Captain': 'Capitão',
    'Major': 'Major',
    'Lieutenant Colonel': 'Tenente-coronel',
    'Colonel': 'Coronel',
    'Brigadier': 'Brigadeiro',
    'Major General': 'General de brigada',
    'Lieutenant General': 'General de divisão',
    'General': 'General de exército',
    'Marshal': 'Marechal',
    'Fieldmarshal': 'Marechal de campo',
    'Commander': 'Comandante',
    'Generalissimo': 'Generalíssimo',*/
    'Coloring_green_paint': 'Pinturaverde',
    'Coloring_celebration1': 'Pinturaferiado',
    'Coloring_red_paint': 'Pinturavermelha',
    'Coloring_blue_paint': 'Pinturaazul',
    'Coloring_black_paint': 'Pinturapreta',
    'Coloring_white_paint': 'Pinturabranca',
    'Coloring_orange_paint': 'Pinturalaranja',
    'Coloring_flora': 'Pinturaflora',
    'Coloring_marine': 'Pinturamarinha',
    'Coloring_swamp': 'Pinturapantano',
    'Coloring_forester': 'Pinturaflorestal',
    'Magma_preview': 'Pinturamagma',
    'Coloring_safari': 'Pinturasafari',
    'Invader_Paint': 'Pinturainvader',
    'Metallic_Paint': 'Pinturametalica',
    'Lava_Paint': 'Pinturalava',
    'Dragon_Paint': 'Pinturadragão',
    'Lead_Paint': 'Pinturachumbo',
    'Mary_Paint': 'Pinturamary',
    'Coloring_storm': 'Pinturatempestade',
    'Coloring_carbon': 'Pinturacarbono',
    'Coloring_roger': 'Pinturacaveira',
    'Fracture_Paint': 'Pinturafratura',
    'Vortex_Paint': 'Pinturavortex',
    'Kolchuga_preview': 'Pinturaringmaiden',
    'Coloring_corrosion': 'Pinturacorrosao',
    'Coloring_tundra': 'Pinturatundra',
    'Coloring_alien': 'Pinturaalienigena',
    'Coloring_swash': 'Pinturamarinho',
    'Pixel_preview': 'Pinturapixel',
    'Guerrilla_Paint': 'Pinturaguerrilha',
    'Coloring_cedar': 'Pinturacedro',
    'Coloring_inlove': 'Pinturaapaixonado',
    'Coloring_desert': 'Pinturadeserto',
    'Coloring_dirty': 'Pinturalama',
    'Coloring_jaguar': 'Pinturajaguar',
    'Coloring_savanna': 'Pinturasavana',
    'Coloring_loam': 'Pinturaargila',
    'Sakura_Paint': 'Pinturasakura',
    'Coloring_urban': 'Pinturaurbana',
    'Coloring_atom': 'Pinturaatomo',
    'Coloring_digital': 'Pinturadigital',
    'Coloring_hohloma': 'Pinturahohloma',
    'Rhino_Paint': 'Pinturarhino',
    'Coloring_electra': 'Pinturaelectra',
    'Cherry_Paint': 'Pinturacereja',
    'Blacksmith_Paint': 'Pinturaferreiro',
    'Coloring_rustle': 'Pinturafarfalha',
    'Coloring_python': 'Pinturapiton',
    'Coloring_sandstone': 'Pinturaarenito',
    'Coloring_spark': 'Pinturafaisca',
    'Coloring_winter': 'Pinturainverno',
    'Coloring_needle': 'Pinturaagulha',
    'Coloring_zeus': 'Pinturazeus',
    'Hive_Paint': 'Pinturacolmeia',
    'Coloring_rock': 'Pinturarocha',
    'Coloring_mars': 'Pinturamarte',
    'Coloring_prodigi': 'Pinturaprodigo',
    'Graffiti_Paint': 'Pinturagrafite',
    'Coloring_irbis': 'Pinturairbis',
    'Coloring_emerald': 'Pinturaesmeralda',
    'Coloring_inferno': 'Pinturainferno',
    'Coloring_nano': 'Pinturanano',
    'Raccoon_Paint': 'Pinturafuaxinim',
    'Coloring_clay': 'Pinturabarro',
    'Coloring_taiga': 'Pinturataiga',
    'Coloring_tiger': 'Pinturatigre',
    'Coloring_jade': 'Pinturajade',
    'Coloring_picasso': 'Pinturapicasso',
    'Lumberjack_Paint': 'Pinturalenhador',
    'Africa_Paint': 'Pinturaafrica',
    'Best_Helper': 'Pinturaajudante',
    'HOTY2022': 'Pinturaajudante_do_Ano',
    'Master_of_parkour2022_paint': 'Pinturamestreparkour2022',
    'Master_of_parkour2023': 'Pinturamestre_do_Parkour_2023',
    'Impulse_paint': 'Pinturapulso',
    'Coloring_acid2': 'Pinturaacid',
    'Star_paint': 'Pinturaestrela',
    'Gladiator_paint': 'Pinturagladiador',
    'ВЕТЕРАН_paint': 'Pinturaveterano',
    'Champion_paint': 'Pinturacampeao',
    'Silver_paint': 'Pinturaprata',
    'Bronze_paint': 'Pinturabronze',
    'Storm1_paint': 'Pinturatempestade',
    'Game_2024_paint': 'PinturaO_JOGO_2024',
    'Alligator_paint': 'Pinturajacare',
    'Aramid_paint': 'Pinturaaramida',
    'Wiki_paint': 'Pinturaeditordowiki',
    'Helios_paint': 'Pinturahelios',
    'Glide': 'Pinturaglide',
    'Cobalt': 'Pinturacobalto',
    'Engineer_paint': 'Pinturaengenheiro',
    'Microship_paint': 'Pinturamicroship',
    'Neon_paint': 'Pinturaneon',
    'Spectator_paint': 'Pinturaespectador',
    'Flame_paint': 'Pinturachama',
    'YouTuber': 'PinturayouTuber',
    '[[File:IconMini_1.png|link=Recruit]]': '{{Rank/01}}',
    '[[File:IconMini_2.png|link=Private]]': '{{Rank/02}}',
    '[[File:IconMini_3.png|link=Gefreiter]]': '{{Rank/03}}',
    '[[File:IconMini_4.png|link=Corporal]]': '{{Rank/04}}',
    '[[File:IconMini_5.png|link=Master Corporal]]': '{{Rank/05}}',
    '[[File:IconMini_6.png|link=Sergeant]]': '{{Rank/06}}',
    '[[File:IconMini_7.png|link=Staff Sergeant]]': '{{Rank/07}}',
    '[[File:IconMini_8.png|link=Master Sergeant]]': '{{Rank/08}}',
    '[[File:IconMini_9.png|link=First Sergeant]]': '{{Rank/09}}',
    '[[File:IconMini_10.png|link=Sergeant-Major]]': '{{Rank/10}}',
    '[[File:IconMini_11.png|link=Warrant Officer 1]]': '{{Rank/11}}',
    '[[File:IconMini_12.png|link=Warrant Officer 2]]': '{{Rank/12}}',
    '[[File:IconMini_13.png|link=Warrant Officer 3]]': '{{Rank/13}}',
    '[[File:IconMini_14.png|link=Warrant Officer 4]]': '{{Rank/14}}',
    '[[File:IconMini_15.png|link=Warrant Officer 5]]': '{{Rank/15}}',
    '[[File:IconMini_16.png|link=Third Lieutenant]]': '{{Rank/16}}',
    '[[File:IconMini_17.png|link=Second Lieutenant]]': '{{Rank/17}}',
    '[[File:IconMini_18.png|link=First Lieutenant]]': '{{Rank/18}}',
    '[[File:IconMini_19.png|link=Captain]]': '{{Rank/19}}',
    '[[File:IconMini_20.png|link=Major]]': '{{Rank/20}}',
    '[[File:IconMini_21.png|link=Lieutenant Colonel]]': '{{Rank/21}}',
    '[[File:IconMini_22.png|link=Colonel]]': '{{Rank/22}}',
    '[[File:IconMini_24.png|link=Major General]]': '{{Rank/24}}',
    '[[File:IconMini_25.png|link=Lieutenant General]]': '{{Rank/25}}',
    '[[File:IconMini_26.png|link=General]]': '{{Rank/26}}',
    '[[File:IconMini_27.png|link=Marshal]]': '{{Rank/27}}',
    '[[File:IconMini_28.png|link=Fieldmarshal]]': '{{Rank/28}}',
    '[[File:IconMini_29.png|link=Commander]]': '{{Rank/29}}',
    '[[File:IconMini_30.png|link=Generalissimo]]': '{{Rank/30}}',
    'Special Group Participants': 'Participantes de grupos especiais',
    'Special': 'Especial',
    'Prize': 'Prêmio',
    '[[File:MiniCry.png|link=]]': '{{price|}}'    
}

function replace(input) {
  for (const [key, value] of Object.entries(WORDS)) {
    input = input.replace(key, value);
  }
  
  return input;
}

document.getElementById('inputCode').addEventListener('input', function(e) {
  document.getElementById('outputCode').value = replace(this.value);
});

document.getElementById('copyBtn').addEventListener('click', function(e) {
  navigator.clipboard.writeText(document.getElementById(this.getAttribute('data-for')).value);
});
