// Hardcode...
// But it's ok

WORDS = {
    'Firebird|Firebird': 'Protelançachamas|Lança-Chamas',
    'Smoky|Smoky': 'Protefumegante|Canhão-Fumegante',
    'Twins|Twins': 'Protegemeos|Gêmeos',
    'Railgun|Railgun': 'Protecanhaoeletrico|Canhão-Elétrico',
    'HammerProt|Hammer': 'Protemartelo|Martelo',
    'Isida|Isida': 'Proteisida|Isida',
    'Vulcan_rez|Vulcan': 'Protevulcao|Vulcão',
    'Thunder|Thunder': 'Protetrovao|Trovão',
    'Freeze|Freeze': 'Protelançagelo|Lança-Gelo',
    'Ricochet|Ricochet': 'Protericochete|Ricochete',
    'Shaft|Shaft': 'Proteshaft|Shaft',

    'Firebird': 'Lança-Chamas',
    'Smoky': 'Canhão-Fumegante',
    'Twins': 'Gêmeos',
    'Railgun': 'Canhão-Elétrico',
    'Hammer': 'Martelo',
    'Isida': 'Isida',
    'Vulcan': 'Vulcão',
    'Thunder': 'Trovão',
    'Freeze': 'Lança-Gelo',
    'Ricochet': 'Ricochete',
    'Shaft': 'Shaft',

    'Wasp': 'Vespa',
    'Hornet': 'Zangão',
    'Hunter': 'Caçador',
    'Viking': 'Viking',
    'Dictator': 'Ditador',
    'Titan': 'Titã',
    'Mammoth': 'Mamute',

    'Main article': 'Artigo Principal',
    'Paints': 'Pinturas',
    'Basic': 'Básica',
    'Crysmini': 'MiniCry',
    /*'Recruit': 'Recruta',
    'Private': 'Soldado',
    'Gefreiter': 'Taifeiro',
    'Corporal': 'Cabo',
    'Master Corporal': 'Taifeiro-mor',
    'Sergeant': 'Sargento',
    'Staff Sergeant': 'Terceiro-sargento',
    'Master Sergeant': 'Segundo-sargento',
    'First Sergeant': 'Primeiro-sargento',
    'Sergeant-Major': 'Sargento-mor',
    'Warrant Officer 1': 'Subtenente 1',
    'Warrant Officer 2': 'Subtenente 2',
    'Warrant Officer 3': 'Subtenente 3',
    'Warrant Officer 4': 'Subtenente 4',
    'Warrant Officer 5': 'Subtenente 5',
    'Third Lieutenant': 'Aspirante-a-Oficial',
    'Second Lieutenant': 'Segundo-tenente',
    'First Lieutenant': 'Primeiro-tenente',
    'Captain': 'Capitão',
    'Major': 'Major',
    'Lieutenant Colonel': 'Tenente-coronel',
    'Colonel': 'Coronel',
    'Brigadier': 'Brigadeiro',
    'Major General': 'General de brigada',
    'Lieutenant General': 'General de divisão',
    'General': 'General de exército',
    'Marshal': 'Marechal',
    'Fieldmarshal': 'Marechal de campo',
    'Commander': 'Comandante',
    'Generalissimo': 'Generalíssimo',*/
    'Coloring_green_paint': 'Pinturaverde',
    'Coloring_celebration1': 'Pinturaferiado',
    'Coloring_red_paint': 'Pinturavermelha',
    'Coloring_blue_paint': 'Pinturaazul',
    'Coloring_black_paint': 'Pinturapreta',
    'Coloring_white_paint': 'Pinturabranca',
    'Coloring_orange_paint': 'Pinturalaranja',
    'Coloring_flora': 'Pinturaflora',
    'Coloring_marine': 'Pinturamarinha',
    'Coloring_swamp': 'Pinturapantano',
    'Coloring_forester': 'Pinturaflorestal',
    'Magma_preview': 'Pinturamagma',
    'Coloring_safari': 'Pinturasafari',
    'Invader_Paint': 'Pinturainvader',
    'Metallic_Paint': 'Pinturametalica',
    'Lava_Paint': 'Pinturalava',
    'Dragon_Paint': 'Pinturadragão',
    'Lead_Paint': 'Pinturachumbo',
    'Mary_Paint': 'Pinturamary',
    'Coloring_storm': 'Pinturatempestade',
    'Coloring_carbon': 'Pinturacarbono',
    'Coloring_roger': 'Pinturacaveira',
    'Fracture_Paint': 'Pinturafratura',
    'Vortex_Paint': 'Pinturavortex',
    'Kolchuga_preview': 'Pinturaringmaiden',
    'Coloring_corrosion': 'Pinturacorrosao',
    'Coloring_tundra': 'Pinturatundra',
    'Coloring_alien': 'Pinturaalienigena',
    'Coloring_swash': 'Pinturamarinho',
    'Pixel_preview': 'Pinturapixel',
    'Guerrilla_Paint': 'Pinturaguerrilha',
    'Coloring_cedar': 'Pinturacedro',
    'Coloring_inlove': 'Pinturaapaixonado',
    'Coloring_desert': 'Pinturadeserto',
    'Coloring_dirty': 'Pinturalama',
    'Coloring_jaguar': 'Pinturajaguar',
    'Coloring_savanna': 'Pinturasavana',
    'Coloring_loam': 'Pinturaargila',
    'Sakura_Paint': 'Pinturasakura',
    'Coloring_urban': 'Pinturaurbana',
    'Coloring_atom': 'Pinturaatomo',
    'Coloring_digital': 'Pinturadigital',
    'Coloring_hohloma': 'Pinturahohloma',
    'Rhino_Paint': 'Pinturarhino',
    'Coloring_electra': 'Pinturaelectra',
    'Cherry_Paint': 'Pinturacereja',
    'Blacksmith_Paint': 'Pinturaferreiro',
    'Coloring_rustle': 'Pinturafarfalha',
    'Coloring_python': 'Pinturapiton',
    'Coloring_sandstone': 'Pinturaarenito',
    'Coloring_spark': 'Pinturafaisca',
    'Coloring_winter': 'Pinturainverno',
    'Coloring_needle': 'Pinturaagulha',
    'Coloring_zeus': 'Pinturazeus',
    'Hive_Paint': 'Pinturacolmeia',
    'Coloring_rock': 'Pinturarocha',
    'Coloring_mars': 'Pinturamarte',
    'Coloring_prodigi': 'Pinturaprodigo',
    'Graffiti_Paint': 'Pinturagrafite',
    'Coloring_irbis': 'Pinturairbis',
    'Coloring_emerald': 'Pinturaesmeralda',
    'Coloring_inferno': 'Pinturainferno',
    'Coloring_nano': 'Pinturanano',
    'Raccoon_Paint': 'Pinturafuaxinim',
    'Coloring_clay': 'Pinturabarro',
    'Coloring_taiga': 'Pinturataiga',
    'Coloring_tiger': 'Pinturatigre',
    'Coloring_jade': 'Pinturajade',
    'Coloring_picasso': 'Pinturapicasso',
    'Lumberjack_Paint': 'Pinturalenhador',
    'Africa_Paint': 'Pinturaafrica',
    'Best_Helper': 'Pinturaajudante',
    'HOTY2022': 'Pinturaajudante_do_Ano',
    'Master_of_parkour2022_paint': 'Pinturamestreparkour2022',
    'Master_of_parkour2023': 'Pinturamestre_do_Parkour_2023',
    'Impulse_paint': 'Pinturapulso',
    'Coloring_acid2': 'Pinturaacid',
    'Star_paint': 'Pinturaestrela',
    'Gladiator_paint': 'Pinturagladiador',
    'ВЕТЕРАН_paint': 'Pinturaveterano',
    'Champion_paint': 'Pinturacampeao',
    'Silver_paint': 'Pinturaprata',
    'Bronze_paint': 'Pinturabronze',
    'Storm1_paint': 'Pinturatempestade',
    'Game_2024_paint': 'PinturaO_JOGO_2024',
    'Alligator_paint': 'Pinturajacare',
    'Aramid_paint': 'Pinturaaramida',
    'Wiki_paint': 'Pinturaeditordowiki',
    'Helios_paint': 'Pinturahelios',
    'Glide': 'Pinturaglide',
    'Cobalt': 'Pinturacobalto',
    'Engineer_paint': 'Pinturaengenheiro',
    'Microship_paint': 'Pinturamicroship',
    'Neon_paint': 'Pinturaneon',
    'Spectator_paint': 'Pinturaespectador',
    'Flame_paint': 'Pinturachama',
    'YouTuber': 'PinturayouTuber',
    '[[File:IconMini_1.png|link=Recruit]]': '{{Rank/01}}',
    '[[File:IconMini_2.png|link=Private]]': '{{Rank/02}}',
    '[[File:IconMini_3.png|link=Gefreiter]]': '{{Rank/03}}',
    '[[File:IconMini_4.png|link=Corporal]]': '{{Rank/04}}',
    '[[File:IconMini_5.png|link=Master Corporal]]': '{{Rank/05}}',
    '[[File:IconMini_6.png|link=Sergeant]]': '{{Rank/06}}',
    '[[File:IconMini_7.png|link=Staff Sergeant]]': '{{Rank/07}}',
    '[[File:IconMini_8.png|link=Master Sergeant]]': '{{Rank/08}}',
    '[[File:IconMini_9.png|link=First Sergeant]]': '{{Rank/09}}',
    '[[File:IconMini_10.png|link=Sergeant-Major]]': '{{Rank/10}}',
    '[[File:IconMini_11.png|link=Warrant Officer 1]]': '{{Rank/11}}',
    '[[File:IconMini_12.png|link=Warrant Officer 2]]': '{{Rank/12}}',
    '[[File:IconMini_13.png|link=Warrant Officer 3]]': '{{Rank/13}}',
    '[[File:IconMini_14.png|link=Warrant Officer 4]]': '{{Rank/14}}',
    '[[File:IconMini_15.png|link=Warrant Officer 5]]': '{{Rank/15}}',
    '[[File:IconMini_16.png|link=Third Lieutenant]]': '{{Rank/16}}',
    '[[File:IconMini_17.png|link=Second Lieutenant]]': '{{Rank/17}}',
    '[[File:IconMini_18.png|link=First Lieutenant]]': '{{Rank/18}}',
    '[[File:IconMini_19.png|link=Captain]]': '{{Rank/19}}',
    '[[File:IconMini_20.png|link=Major]]': '{{Rank/20}}',
    '[[File:IconMini_21.png|link=Lieutenant Colonel]]': '{{Rank/21}}',
    '[[File:IconMini_22.png|link=Colonel]]': '{{Rank/22}}',
    '[[File:IconMini_24.png|link=Major General]]': '{{Rank/24}}',
    '[[File:IconMini_25.png|link=Lieutenant General]]': '{{Rank/25}}',
    '[[File:IconMini_26.png|link=General]]': '{{Rank/26}}',
    '[[File:IconMini_27.png|link=Marshal]]': '{{Rank/27}}',
    '[[File:IconMini_28.png|link=Fieldmarshal]]': '{{Rank/28}}',
    '[[File:IconMini_29.png|link=Commander]]': '{{Rank/29}}',
    '[[File:IconMini_30.png|link=Generalissimo]]': '{{Rank/30}}',
    
    'IconsNormal ': 'IconsNormal_',
    'Staff_Sergeant': 'Staff Sergeant',
    '[[File:IconsNormal_01.png|link=Recruit]]': '{{Rank/01}}',
    '[[File:IconsNormal_02.png|link=Private]]': '{{Rank/02}}',
    '[[File:IconsNormal_03.png|link=Gefreiter]]': '{{Rank/03}}',
    '[[File:IconsNormal_04.png|link=Corporal]]': '{{Rank/04}}',
    '[[File:IconsNormal_05.png|link=Master Corporal]]': '{{Rank/05}}',
    '[[File:IconsNormal_06.png|link=Sergeant]]': '{{Rank/06}}',
    '[[File:IconsNormal_07.png|link=Staff Sergeant]]': '{{Rank/07}}',
    '[[File:IconsNormal_08.png|link=Master Sergeant]]': '{{Rank/08}}',
    '[[File:IconsNormal_09.png|link=First Sergeant]]': '{{Rank/09}}',
    '[[File:IconsNormal_10.png|link=Sergeant-Major]]': '{{Rank/10}}',
    '[[File:IconsNormal_11.png|link=Warrant Officer 1]]': '{{Rank/11}}',
    '[[File:IconsNormal_12.png|link=Warrant Officer 2]]': '{{Rank/12}}',
    '[[File:IconsNormal_13.png|link=Warrant Officer 3]]': '{{Rank/13}}',
    '[[File:IconsNormal_14.png|link=Warrant Officer 4]]': '{{Rank/14}}',
    '[[File:IconsNormal_15.png|link=Warrant Officer 5]]': '{{Rank/15}}',
    '[[File:IconsNormal_16.png|link=Third Lieutenant]]': '{{Rank/16}}',
    '[[File:IconsNormal_17.png|link=Second Lieutenant]]': '{{Rank/17}}',
    '[[File:IconsNormal_18.png|link=First Lieutenant]]': '{{Rank/18}}',
    '[[File:IconsNormal_19.png|link=Captain]]': '{{Rank/19}}',
    '[[File:IconsNormal_20.png|link=Major]]': '{{Rank/20}}',
    '[[File:IconsNormal_21.png|link=Lieutenant Colonel]]': '{{Rank/21}}',
    '[[File:IconsNormal_22.png|link=Colonel]]': '{{Rank/22}}',
    '[[File:IconsNormal_23.png|link=Brigadier]]': '{{Rank/23}}',
    '[[File:IconsNormal_24.png|link=Major General]]': '{{Rank/24}}',
    '[[File:IconsNormal_25.png|link=Lieutenant General]]': '{{Rank/25}}',
    '[[File:IconsNormal_26.png|link=General]]': '{{Rank/26}}',
    '[[File:IconsNormal_27.png|link=Marshal]]': '{{Rank/27}}',
    '[[File:IconsNormal_28.png|link=Fieldmarshal]]': '{{Rank/28}}',
    '[[File:IconsNormal_29.png|link=Commander]]': '{{Rank/29}}',
    '[[File:IconsNormal_30.png|link=Generalissimo]]': '{{Rank/30}}',
    'Special Group Participants': 'Participantes de grupos especiais',
    'Special': 'Especial',
    'Prize': 'Prêmio',
    '[[File:MiniCry.png|link=]]': '{{price|}}',
    'except': 'exceto',
    'Hull': 'Carroceria',
    'Turret': 'Torreta',
    'Paint': 'Pintura',
    'Green': 'Verde',
    'Holiday': 'Feriado',
    'Red': 'Vermelha',
    'Blue': 'Azul',
    'Black': 'Preta',
    'White': 'Branca',
    'Orange': 'Laranja',
    'Flora': 'Flora',
    'Swamp': 'Pântano',
    'Forest': 'Florestal',
    'Magma': 'Magma',
    'Safari': 'Safari',
    'Invader': 'Invader',
    'Metallic': 'Metálica',
    'Lava': 'Lava',
    'Dragon': 'Dragão',
    'Lead': 'Chumbo',
    'Mary': 'Mary',
    'Storm': 'Tempestade',
    'Carbon': 'Carbono',
    'Roger': 'Caveira',
    'Fracture': 'Fratura',
    'Vortex': 'Vortex',
    'Ringmaiden': 'Ringmaiden',
    'Corrosion': 'Corrosão',
    'Tundra': 'Tundra',
    'Alien': 'Alienígena',
    'Marine': 'Marinho',
    'Pixel': 'Pixel',
    'Guerrilla': 'Guerrilha',
    'Cedar': 'Cedro',
    'Lovestruck': 'Apaixonado',
    'Desert': 'Deserto',
    'Dirty': 'Lama',
    'Jaguar': 'Jaguar',
    'Savanna': 'Savâna',
    'Clay': 'Argila',
    'Sakura': 'Sakura',
    'Urban': 'Urbana',
    'Atom': 'Átomo',
    'Digital': 'Digital',
    'Hohloma': 'Hohloma',
    'Rhino': 'Rhino',
    'Electra': 'Electra',
    'Cherry': 'Cereja',
    'Blacksmith': 'Ferreiro',
    'Rustle': 'Farfalha',
    'Python': 'Píton',
    'Sandstone': 'Arenito',
    'Spark': 'Faísca',
    'Winter': 'Inverno',
    'Needle': 'Agulha',
    'Zeus': 'Zeus',
    'Hive': 'Colmeia',
    'Rock': 'Rocha',
    'Mars': 'Marte',
    'Prodigy': 'Prodígio',
    'Graffiti': 'Grafite',
    'Irbis': 'Irbis',
    'Emerald': 'Esmeralda',
    'Inferno': 'Inferno',
    'Nano': 'Nano',
    'Raccoon': 'Guaxinim',
    'Clay': 'Barro',
    'Taiga': 'Taiga',
    'Tiger': 'Tigre',
    'Jade': 'Jade',
    'Picasso': 'Picasso',
    'Lumberjack': 'Lenhador',
    'Africa': 'Africa',

    'The supplier': 'O fornecedor',
    'Collector': 'Colecionador',
    'Full': 'Completo',
    'Saboteur': 'Sabotador',
    'Stormtrooper': 'Stormtrooper',
    'Brick': 'Tijolo',
    'Almighty': 'Poderoso',
    'Cadet': 'Cadete',
    'Decree': 'Decreto',
    'Universal soldier': 'Soldado Universal',
    'Nidavellir': 'Niõavellir',
    'Zenyatta': 'Zenyatta',
    'Military Doctor': 'Médico militar',
    'Geyser': 'Geyser',
    'Yin yang': 'Yin yang',
    'Krakatau': 'Krakatoa',
    'Varan': 'Varan',
    'Alien': 'Alienígena',
    'Bomber': 'Bombista',
    'Berserk': 'Berserk',
    'Commando': 'Comando',
    'Invisible': 'Invisível',
    'Bunker': 'Bunker',
    'Siberian': 'Siberiano',
    'Pirate': 'Pirata',
    'Firefly': 'Vaga-lume',
    'Savage': 'Lagarto',
    'Lizard': 'Lagarto',
    'Keeper': 'Guardador',
    'Tsunami': 'Tsunami',
    'Mjolnir': 'Mjolnir',
    'Vampire': 'Vampiro',
    'Hero': 'Herói',
    'Anvil': 'Anvil',
    'Reaper': 'Reaper',
    'Exterminator': 'Exterminador',
    'Bulldog': 'Bulldog',
    'Gunslinger': 'Pistoleiro',
    'Blizzard': 'Nevasca',
    'Buffalo': 'Búfalo',
    'Die Hard': 'Die Hard',
    'Matrix': 'Matriz',
    'Cupid': 'Cupido',
    'Knight': 'Cavaleiro',
    'Piranha': 'Piranha',
    'Striker': 'Grevista',
    'Hooligan': 'Hooligan',
    'Fujiyama': 'Fujiyama',
    'Predator': 'Predador',
    'Firewall': 'Guarda-fogo',
    'Aborigine': 'Aborígene',
    'Corsair': 'Corsário',
    'Firebolt': 'Relâmpago',
    'Mosquito': 'Mosquito',
    'Pitbull': 'Pitbull',
    'Atlas': 'Atlas',
    'Ram': 'Carneiro',
    'Osaka': 'Osaka',
    'Voltage': 'Voltagem',
    'Jam': 'Geleia',
    'Anaconda': 'Anaconda',
    'Stinger': 'Ferrão',
    'Tornado': 'Tornado',
    'Firework': 'Fogos de artifício',
    'Simoom': 'Furacão',
    'Guard': 'Guarda',
    'Avalanche': 'Avalanche',
    'Boar': 'Javali',
    'Fortress': 'Fortaleza',
    'Goalkeeper': 'Guarda-redes',
    'Terminator': 'Terminator',
    'Vesuvius': 'Vesúvio',
    'Annihilator': 'Aniquilador',
    'Cyclops': 'Ciclope',
    'Dj': 'Dj',
    'Ice': 'Gelo',
    'Juggler': 'Malabarista',
    'Chiropractor': 'Quiroprata',
    'Northerner': 'Nortenho',
    'Hail': 'Neve',
    'Prometheus': 'Prometheus',
    'Minotaur': 'Minotauro',
    'Ghost': 'Fantasma',
    'Vandal': 'Vândalo',
    'Pyromancer': 'Pyromancer',
    'Cardinal': 'Cardeal',
    'Guardian': 'Guardião',
    'Touche': 'Touche',
    'Nomad': 'Nômade',
    'Ant': 'Formiga',
    'Academician': 'Acadêmico',
    'Thunderer': 'Thunderer',
    'Cliff': 'Penhasco',
    'Giraffe': 'Girafa',
    'Man o War': 'Guerreiro',
    'Bumblebee': 'Bumblebee',
    'Legend': 'Lenda',
    'Healer': 'Curandeiro',
    'Boreas': 'Boreas',
    'Bulldozer': 'Escavadeira',
    'Redneck': 'Camponês',
    'Maestro': 'Maestro',
    'Giant': 'Gigante',
    'Rock climber': 'Alpinista',
    'Eyjafjallajokull': 'Eyjafjallajokull',
    'Destroyer': 'Destruidor',
    'Centaur': 'Centauro',
    'Jackhammer': 'Martelo de demolição',
    'Stonecutter': 'Pedreiro',
    'Sniper': 'Sniper',
    'Fridge': 'Geladeira',
    'Medic': 'Medic',
    'Raiden': 'Raiden',
    'Paladin': 'Paladino',
    'Master of the taiga': 'Milícia',
    'Hammer of Thor': 'Martelo de Thor',
    'Storm': 'Storm',
    'O fornecedor.png': 'The supplier.png',
    'Colecionador.png': 'Collector.png',
    'Completo.png': 'Full.png',
    'Sabotador.png': 'Saboteur.png',
    'Stormtrooper.png': 'Stormtrooper.png',
    'Tijolo.png': 'Brick.png',
    'Poderoso.png': 'Almighty.png',
    'Cadete.png': 'Cadet.png',
    'Decreto.png': 'Decree.png',
    'Soldado Universal.png': 'Universal soldier.png',
    'Niõavellir.png': 'Nidavellir.png',
    'Zenyatta.png': 'Zenyatta.png',
    'Médico militar.png': 'Military Doctor.png',
    'Geyser.png': 'Geyser.png',
    'Yin yang.png': 'Yin yang.png',
    'Krakatoa.png': 'Krakatau.png',
    'Varan.png': 'Varan.png',
    'Alienígena.png': 'Alien.png',
    'Bombista.png': 'Bomber.png',
    'Berserk.png': 'Berserk.png',
    'Comando.png': 'Commando.png',
    'Invisível.png': 'Invisible.png',
    'Bunker.png': 'Bunker.png',
    'Siberiano.png': 'Siberian.png',
    'Pirata.png': 'Pirate.png',
    'Vaga-lume.png': 'Firefly.png',
    'Lagarto.png': 'Lizard.png',
    'Guardador.png': 'Keeper.png',
    'Tsunami.png': 'Tsunami.png',
    'Vampiro.png': 'Vampire.png',
    'Herói.png': 'Hero.png',
    'Anvil.png': 'Anvil.png',
    'Reaper.png': 'Reaper.png',
    'Exterminador.png': 'Exterminator.png',
    'Bulldog.png': 'Bulldog.png',
    'Pistoleiro.png': 'Gunslinger.png',
    'Nevasca.png': 'Blizzard.png',
    'Búfalo.png': 'Buffalo.png',
    'Die Hard.png': 'Die Hard.png',
    'Matriz.png': 'Matrix.png',
    'Cupido.png': 'Cupid.png',
    'Cavaleiro.png': 'Knight.png',
    'Piranha.png': 'Piranha.png',
    'Grevista.png': 'Striker.png',
    'Hooligan.png': 'Hooligan.png',
    'Fujiyama.png': 'Fujiyama.png',
    'Predador.png': 'Predator.png',
    'Guarda-fogo.png': 'Firewall.png',
    'Aborígene.png': 'Aborigine.png',
    'Corsário.png': 'Corsair.png',
    'Relâmpago.png': 'Firebolt.png',
    'Mosquito.png': 'Mosquito.png',
    'Pitbull.png': 'Pitbull.png',
    'Atlas.png': 'Atlas.png',
    'Carneiro.png': 'Ram.png',
    'Osaka.png': 'Osaka.png',
    'Voltagem.png': 'Voltage.png',
    'Geleia.png': 'Jam.png',
    'Anaconda.png': 'Anaconda.png',
    'Ferrão.png': 'Stinger.png',
    'Tornado.png': 'Tornado.png',
    'Fogos de artifício.png': 'Firework.png',
    'Furacão.png': 'Simoom.png',
    'Guarda.png': 'Guard.png',
    'Avalanche.png': 'Avalanche.png',
    'Javali.png': 'Boar.png',
    'Fortaleza.png': 'Fortress.png',
    'Guarda-redes.png': 'Goalkeeper.png',
    'Vesúvio.png': 'Vesuvius.png',
    'Aniquilador.png': 'Annihilator.png',
    'Ciclope.png': 'Cyclops.png',
    'Dj.png': 'Dj.png',
    'Gelo.png': 'Ice.png',
    'Malabarista.png': 'Juggler.png',
    'Quiroprata.png': 'Chiropractor.png',
    'Nortenho.png': 'Northerner.png',
    'Neve.png': 'Hail.png',
    'Prometheus.png': 'Prometheus.png',
    'Minotauro.png': 'Minotaur.png',
    'Fantasma.png': 'Ghost.png',
    'Vândalo.png': 'Vandal.png',
    'Pyromancer.png': 'Pyromancer.png',
    'Cardeal.png': 'Cardinal.png',
    'Guardião.png': 'Guardian.png',
    'Touche.png': 'Touche.png',
    'Nômade.png': 'Nomad.png',
    'Formiga.png': 'Ant.png',
    'Acadêmico.png': 'Academician.png',
    'Thunderer.png': 'Thunderer.png',
    'Penhasco.png': 'Cliff.png',
    'Girafa.png': 'Giraffe.png',
    'Guerreiro.png': 'Man o War.png',
    'Bumblebee.png': 'Bumblebee.png',
    'Lenda.png': 'Legend.png',
    'Curandeiro.png': 'Healer.png',
    'Boreas.png': 'Boreas.png',
    'Escavadeira.png': 'Bulldozer.png',
    'Camponês.png': 'Redneck.png',
    'Maestro.png': 'Maestro.png',
    'Gigante.png': 'Giant.png',
    'Alpinista.png': 'Rock climber.png',
    'Eyjafjallajokull.png': 'Eyjafjallajokull.png',
    'Destruidor.png': 'Destroyer.png',
    'Centauro.png': 'Centaur.png',
    'Martelo de demolição.png': 'Jackhammer.png',
    'Pedreiro.png': 'Stonecutter.png',
    'Sniper.png': 'Sniper.png',
    'Geladeira.png': 'Fridge.png',
    'Medic.png': 'Medic.png',
    'Raiden.png': 'Raiden.png',
    'Paladino.png': 'Paladin.png',
    'Milícia.png': 'Master of the taiga.png',
    'Martelo de Thor.png': 'Hammer of Thor.png',
    'Storm.png': 'Storm.png'
}

function replace(input) {
  for (const [key, value] of Object.entries(WORDS)) {
    input = input.replaceAll(key, value);
  }
  
  return input;
}

document.getElementById('inputCode').addEventListener('input', function(e) {
  document.getElementById('outputCode').value = replace(this.value);
});

document.getElementById('copyBtn').addEventListener('click', function(e) {
  navigator.clipboard.writeText(document.getElementById(this.getAttribute('data-for')).value);
});
